### ISSUE TITLE
Cannot find module 'ng-google-analytics'

### ISSUE THREAD

**Issue by dipedro** [rafanoli/ng-google-analytics#3]
Estou com esse problema ao importar a biblioteca no arquivo app.modules no meu projeto Angular 7.

Dei o npm e a pasta está lá no node_modules, mas fica dando esse erro.

Essa biblioteca dá suporte ao Angular 7?

**Comment by rafanoli** [comment]
@dipedro dá sim! Pode mostrar o seu package.json? e se possível mandar o repo do projeto.
